### ISSUE TITLE
Question: ConfigurationManager

### ISSUE THREAD

**Issue by NelsonLamprecht** [dheida1/Saml2Core#1]
I get an exception when I am using the bare minum configuration otptions about a configuration manager being null; Obviously I am not setting it but I don't see it being set in the demo project: 
Here is my configuration:

services.AddAuthentication(sharedOptions =>
            {
                sharedOptions.DefaultScheme = CookieAuthenticationDefaults.AuthenticationScheme;
                sharedOptions.DefaultSignInScheme = CookieAuthenticationDefaults.AuthenticationScheme;
            }).AddSamlCore(options =>
            {
                options.ServiceProvider.EntityId = "xyz.com";
                options.ServiceProvider.X509Certificate2 =
                    new Cryptography.X509Certificates.Extension.X509Certificate2(
                        "123",
                        StoreName.Root,
                        StoreLocation.LocalMachine,
                        X509FindType.FindBySerialNumber);
                options.WantAssertionsSigned = true;
                options.RequireMessageSigned = true;
                options.Events.OnRemoteFailure = context =>
                {
                    Debugger.Break();
                    return Task.FromResult(0);
                };
                options.Events.OnTicketReceived = context =>
                {
                    Debugger.Break();
                    return Task.FromResult(0);
                };
            });

**Comment by P00159894** [comment]
Hi Nelson, you are missing the Identity Provider metadata address. Add this line and provide the correct value. 

options.MetadataAddress = [IdentityProviderMetadataAddressUrl];

The middleware creates the configuration manager using the Identity Provider metadata address.
