### ISSUE TITLE
SamlCore not found when nuget package is installed

### ISSUE THREAD

**Issue by herlihalim** [dheida1/Saml2Core#3]
I started a new solution with template, add saml2core version 3.0 as nuget package.

However, when trying to use it.

using SamlCore.AspNetCore.Authentication.Saml2.Metadata

`.AddSamlCore(options =>`

I received the below error.

> The type or namespace name 'SamlCore' could not be found (are you missing a using directive or an assembly reference?)

**Comment by dheida1** [comment]
Try again now. The 'lib' folder wasn't uploaded for some reason. The latest version is now v3.1.0.  
Let me know if there are any issues.

**Comment by herlihalim** [comment]
Thank you! It works now.
