### ISSUE TITLE
Context.User.Identity.Name is returning null

### ISSUE THREAD

**Issue by angel7170** [dheida1/Saml2Core#4]
Hello,

I deployed this solution in our environment. So far SAML authentication works but we are not able to convert the SAML assertions into claims. The SAML name attribute urn:oid:0.9.2342.19200300.100.1.1 holds the username and we want to convert this to claims. 
I tried modifying the code as below but it still doesn't work. Could you please tell if there is anything I need to change? Thank you

 `var identity = context.Principal.Identity as ClaimsIdentity;
           var claims = context.Principal.Claims;                 
           if (claims.Any(c => c.Type == "urn:oid:0.9.2342.19200300.100.1.1"))
           {
               var userId = claims.FirstOrDefault(c => c.Type == "urn:oid:0.9.2342.19200300.100.1.1").Value;
               var name = claims.FirstOrDefault(c => c.Type == ClaimTypes.Name);
               identity.TryRemoveClaim(name);
               identity.AddClaim(new Claim(ClaimTypes.Name, userId));
           }`

**Comment by dheida1** [comment]
Hi @angel7170 ,

Let's check what is coming in. Add the lines below for the principle, put a break point and step through and check what is showing up. Let me know what you see. 

```C#
           options.Events.OnTicketReceived = context =>
breakpoint ---> {  
                               var principle = context.Principle;
                               var identity = context.Principal.Identity as ClaimsIdentity;
                               var claims = context.Principal.Claims;
                                if (principle.HasClaim(c => c.Type == "urn:oid:0.9.2342.19200300.100.1.1"))
                              {
                                   var name = principle..FindFirst("urn:oid:0.9.2342.19200300.100.1.1");                                  
                                  identity.AddClaim(new Claim(ClaimTypes.Name, userId));
                              }
                               return Task.FromResult(0);
                 };
```
