### ISSUE TITLE
[Question] Licence missmatch?

### ISSUE THREAD

**Issue by TheSchmu** [dheida1/Saml2Core#6]
Good morning,

we were wondering about the current valid licence of saml2core. The licence info on https://www.nuget.org/packages/SAML2Core/
redirects to MIT licence text, whereas the LICENCE file in your repo clearly states GPL3.

We're asking because we believe to have found an issue with Azure AD (and not necessarily your library!), in which signature validation fails due to the fact that Azure AD does not provide valid xml (missing ds-prefix in signature type / element). We would be able to change according to our requirements (which would then void usage for any other provider but those are no use case for us at the moment anyways), unfortunately not under the restrictions of GPL3 however.

Thank you very much in advance for a quick response!
Best regards.

**Comment by dheida1** [comment]
@TheSchmu , yes it is a mismatch! You can go ahead and make you changes. I'd appreciate it if you could provide the fix you used to help others if they are in the same situation.

Thanks!
